import { Transaction } from "@/type";

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    title: "Monthly Salary",
    category: "salary",
    amount: 5000.0,
    type: "income",
    date: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Freelance Project",
    category: "freelance",
    amount: 1200.0,
    type: "income",
    date: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "3",
    title: "Birthday Gift",
    category: "gift",
    amount: 100.0,
    type: "income",
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "4",
    title: "Stock Dividend",
    category: "investment",
    amount: 50.0,
    type: "income",
    date: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "5",
    title: "Grocery Shopping",
    category: "food",
    amount: 150.75,
    type: "expense",
    date: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Uber Ride",
    category: "transport",
    amount: 25.5,
    type: "expense",
    date: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "7",
    title: "New Sneakers",
    category: "shopping",
    amount: 120.0,
    type: "expense",
    date: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "8",
    title: "Cinema Date",
    category: "entertainment",
    amount: 45.0,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "9",
    title: "Electricity Bill",
    category: "bills",
    amount: 85.2,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "10",
    title: "Pharmacy",
    category: "health",
    amount: 30.0,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "11",
    title: "Online Course",
    category: "education",
    amount: 19.99,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "12",
    title: "Miscellaneous",
    category: "other",
    amount: 10.0,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "13",
    title: "Bonus Payout",
    category: "salary",
    amount: 800.0,
    type: "income",
    date: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "14",
    title: "Restaurant Dinner",
    category: "food",
    amount: 65.0,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "15",
    title: "Gym Membership",
    category: "health",
    amount: 45.0,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: "16",
    title: "Logo Design Gig",
    category: "freelance",
    amount: 350.0,
    type: "income",
    date: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "17",
    title: "Train Ticket",
    category: "transport",
    amount: 12.0,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "18",
    title: "Water Bill",
    category: "bills",
    amount: 28.5,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 11).toISOString(),
  },
  {
    id: "19",
    title: "Book Purchase",
    category: "education",
    amount: 15.99,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    id: "20",
    title: "Concert Tickets",
    category: "entertainment",
    amount: 75.0,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 13).toISOString(),
  },
  {
    id: "21",
    title: "Clothing Haul",
    category: "shopping",
    amount: 200.0,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 14).toISOString(),
  },
  {
    id: "22",
    title: "Investment Return",
    category: "investment",
    amount: 120.0,
    type: "income",
    date: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "23",
    title: "Coffee & Snacks",
    category: "food",
    amount: 8.5,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "24",
    title: "App Subscription",
    category: "entertainment",
    amount: 9.99,
    type: "expense",
    date: new Date(Date.now() - 86400000 * 16).toISOString(),
  },
  {
    id: "25",
    title: "Birthday Money",
    category: "gift",
    amount: 200.0,
    type: "income",
    date: new Date(Date.now() - 86400000 * 17).toISOString(),
  },
];
